from sfi.common.text import normalize_chars, strip_print_furniture


def test_curly_apostrophe_matches_straight():
    # rider-2 pin: a label differing ONLY by apostrophe form must match.
    assert normalize_chars("Total shareholders’ equity") == normalize_chars(
        "Total shareholders' equity"
    )


def test_nbsp_matches_plain_space():
    assert normalize_chars("Total assets") == normalize_chars("Total assets")


def test_nothing_else_loosens():
    # Case, dashes, and interior whitespace differences must still mismatch.
    assert normalize_chars("Gross margin") != normalize_chars("gross margin")
    assert normalize_chars("Cost–of–sales") != normalize_chars("Cost-of-sales")
    assert normalize_chars("Totalassets") != normalize_chars("Total assets")


PAGE = (
    "7/12/26, 6:53 PM tsla-20251231\n"
    "Tesla, Inc.\n"
    "Consolidated Balance Sheets\n"
    "(in millions, except per share data)\n"
    "Cash and cash equivalents 16,139 16,139\n"
    "612\n"  # a bare number INSIDE the table must survive
    "Total assets 122,070 121,349\n"
    "49\n"
    "https://www.sec.gov/Archives/edgar/data/1318605/000162828026003952/tsla-20251231.htm 81/159"
)


def test_strips_header_url_and_trailing_folio():
    stripped = strip_print_furniture(PAGE)
    lines = stripped.splitlines()
    assert lines[0] == "Tesla, Inc."
    assert lines[-1] == "Total assets 122,070 121,349"
    assert "6:53" not in stripped
    assert "81/159" not in stripped


def test_interior_bare_number_survives():
    assert "612" in strip_print_furniture(PAGE).splitlines()


def test_footer_only_spillover_page_strips_to_empty():
    spillover = (
        "7/12/26, 6:53 PM tsla-20251231\n"
        "49\n"
        "https://www.sec.gov/Archives/edgar/data/1318605/000162828026003952/tsla-20251231.htm 81/159"
    )
    assert strip_print_furniture(spillover) == ""


def test_apple_folio_footer_stripped():
    page = "Apple Inc. | Q2 2026 Form 10-Q | 3\nCash generated by operating activities 71,000"
    assert strip_print_furniture(page) == "Cash generated by operating activities 71,000"


def test_strips_layout_padded_furniture():
    # extract_text(layout=True) pads with space runs; furniture must still go.
    page = (
        "   7/12/26, 6:58 PM                          aapl-20250927\n"
        "                                       Apple Inc.\n"
        "     Net income                                  $    112,010 $  93,736 $  96,995\n"
        "                                          50\n"
        "https://www.sec.gov/Archives/edgar/data/320193/000032019325000079/aapl-20250927.htm   45/77"
    )
    stripped = strip_print_furniture(page)
    assert "6:58" not in stripped and "45/77" not in stripped
    assert stripped.splitlines()[-1].strip().startswith("Net income")


def test_grounding_token_set_excludes_furniture_tokens():
    # rider-3 pin (token-set level): tokens appearing only in the stripped
    # header/footer are absent after stripping.
    tokens = set(strip_print_furniture(PAGE).split())
    for furniture_only in ("7/12/26,", "6:53", "PM", "tsla-20251231", "81/159", "49"):
        assert furniture_only not in tokens
